### ISSUE TITLE
ESC-50 results with audiovisual self-supervised learning

### ISSUE THREAD

**Issue by DTaoo** [karolpiczak/ESC-50#12]
Hi Karolpiczak,
    Thanks for organizing this repo for facilitating the development on sound event reg. In 2019, we have published one work @ CVPR2019, which is the first work that suppresses the human accuracy with audiovisual self-supervised learning approach, i.e., < Deep Multimodal Clustering for Unsupervised Audiovisual Learning>. Here is the link: http://openaccess.thecvf.com/content_CVPR_2019/html/Hu_Deep_Multimodal_Clustering_for_Unsupervised_Audiovisual_Learning_CVPR_2019_paper.html

We do hope that you could append our previous work in your next update.

Best,
Di

**Comment by karolpiczak** [comment]
Hi,

thanks for the notification. The leader board is a bit outdated, and I plan to overhaul the whole concept. As the number of papers evaluated on ESC-50 has surpassed my initial expectations, I would like to present them in a more useful manner. I'm not sure what's the ETA for this, if I can't manage this in the upcoming weeks, I will try to batch such smaller updates to the table.

**Comment by dav-ell** [comment]
I would be very much in support of this!

I'm currently working on research on Transformers applied to ESC, and, though the use of Transformers is so far rather limited due to the lack of large-scale ESC datasets, I can see new state of the arts being set by Transformers in the next few years. This list would certainly be a useful part of the ESC community as that evolves.
